name: DevSecOps Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    name: Basic Security Checks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Simple file structure validation
    - name: Check Project Structure
      run: |
        echo "🔍 Checking project structure..."
        ls -la
        echo "✅ Project structure check complete"

  terraform-validation:
    runs-on: ubuntu-latest
    name: Terraform Validation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
    
    - name: Terraform Format Check
      working-directory: ./terraform
      run: terraform fmt -check
    
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init -backend=false
    
    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate
    
    - name: Run TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest
    
    - name: Init TFLint
      working-directory: ./terraform
      run: tflint --init
    
    - name: Run TFLint
      working-directory: ./terraform
      run: tflint

  frontend-security:
    runs-on: ubuntu-latest
    name: Frontend Security
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      continue-on-error: true
    
    - name: Run npm audit (non-blocking)
      working-directory: ./frontend
      run: npm audit --audit-level=high
      continue-on-error: true
    
    - name: Basic TypeScript Check
      working-directory: ./frontend
      run: npx tsc --noEmit
      continue-on-error: true